name       : xsd
version    : 4.0.0
release    : 1
source     :
    - http://www.codesynthesis.com/download/xsd/4.0/xsd-4.0.0+dep.tar.bz2 : eca52a9c8f52cdbe2ae4e364e4a909503493a0d51ea388fc6c9734565a859817
license    : GPL-2.0
component  : programming.tools
summary    : CodeSynthesis XSD is an W3C XML Schema to C++ data binding compiler
description: |
    CodeSynthesis XSD is an open-source, cross-platform W3C XML Schema to C++ data binding compiler. Provided with an XML instance specification (XML Schema), it generates C++ classes that represent the given vocabulary as well as XML parsing and serialization code. You can then access the data stored in XML using types and functions that semantically correspond to your application domain rather than dealing with the intricacies of reading and writing XML.
builddeps  :
    - pkgconfig(libcutl)
    - pkgconfig(xerces-c)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/xsdcxx-rename.patch
build      : |
    %make BOOST_LINK_SYSTEM=y EXTERNAL_LIBCUTL=y
install    : |
    make install_prefix=$installdir/usr install
    # Rename files to xsdcxx to avoid name conflicts with mono
    mv $installdir/usr/bin/xsd{,cxx}
    mv $installdir/usr/share/man/man1/xsd{,cxx}.1
